apiVersion: v1.2
kind: replicaset
metadata:
  name: front-end
  labels:
    app: flipkart
    tier: front-end
spec:
  replicas: 3
  selector:
    app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80


# kubectl apply -f repilcaset.yml  
#This command applies the configuration specified in the replicaset.yml file to the Kubernetes cluster.

# kubectl get rs
#This command retrieves and displays a list of all ReplicaSets in the current Kubernetes namespace.

# kubectl describe name
#This command provides detailed information about a specific ReplicaSet identified by its name (<name>).
